spring:
  application:
    name: forum
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bess_forum_db
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
server:
  port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
